from src.execution.cnn_tuning_exec import CNNTuningExecution
from src.execution.data_splitting_exec import DataSplittingExecution
from src.execution.window_splitting_exec import WindowSplittingExecution
from src.execution.cnn_training_exec import CNNTrainingExecution
from src.execution.cnn_validation_exec import CNNValidationExecution
from src.execution.cnn_soft_start_exec import CNNSoftStartExecution